### PR TITLE
Adding toolflow support for generating .fpg file for alveo cards

### PR DESCRIPTION
**Pull request by mchirindo**
The generated .fpg file will be based on 'top.bt' for the alveo, contrary to 'top.bin' for other platforms.

### CODE REVIEW

**Review by AdamI75 — COMMENTED** [review]
@mchirindo I am thinking we should rather name the platform as "alveo" as I assume whether it is an au50 or au280, there will be other versions of alveo that we will need to update as we add? If we call it alveo then no more changes would be needed? This is the only issue I see before approving this.

**Comment by mchirindo** [comment]
Hi Adam

I think the known platform names are derived from the existing yaml files
(au50.yaml and au280.yaml) in jasper_library/platforms (I might be wrong).
If this is the case, I wonder if all alveos could have the same .yaml file.
I guess they need to be different. @Wesley New ***@***.***> may
enlighten here.

**Comment by AdamI75** [comment]
@mchirindo No, the yaml files will need to be different as different FPGAs require different pinouts. I am wondering if we should leave it as is for now. @wnew if you are happy to leave it for now then we can approve and move on?

**Comment by wnew** [comment]
Thanks for this work Mathews. Looks good

**Pull request merged**
