### PR TITLE
Converting dec to hex on software register

### PR DESCRIPTION
**Pull request by mchirindo**

### CODE REVIEW

**Comment by wnew** [comment]
Just busy researching why all these commits are listed here. It should only be the last one.

**Comment by AdamI75** [comment]
@wnew and @mchirindo, what is happening with this pull request? Have you finished your investigation yet?

**Comment by wnew** [comment]
@mchirindo Do you recall why xps_library.slx and software_register.slx  were updated?

**Comment by mchirindo** [comment]
@Wesley New <wesley@ska.ac.za> the update was meant to convert the software
register initial value from decimal to hexadecimal as required in the
jasper.per file.
Originally an initial value that you enter as a decimal number would simply
appear as the same number (now as hex) without proper conversion.

**Comment by AdamI75** [comment]
@wnew and @mchirindo: I have seen this pull request for some time. If it can be merged then let's do so. If it needs testing then please do so. Create a jira ticket if necessary, thanks.

**Comment by mchirindo** [comment]
I am closing this pull request to open a new one that does not include all the irrelevant commits.

**Pull request closed without merging**
